// "use client"

import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { poppins } from "@/components/ui/font";
import { Footer } from "@/components/Footer";
// import dynamic from 'next/dynamic';

// const Navbar = dynamic(() => import('../components/Navbar'), { ssr: false });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased mt-5 mx-12 ${poppins.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
